# Generated by Django 2.0.6 on 2018-09-13 05:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('english', '0003_problem_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='english.Problem'),
        ),
    ]
