# Generated by Django 2.0.6 on 2018-09-13 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('english', '0004_problem_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
