# Generated by Django 2.0.6 on 2018-09-13 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('english', '0005_auto_20180913_1354'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='booking_manager',
            field=models.BooleanField(default=False),
        ),
    ]
